### PR TITLE
[FEATURE] Add an option "rather not say" for the gender

### PR DESCRIPTION
**Pull request by oliverklee**
It should be possible to have the gender field in the form while still make it non-required.

Also make the "rather not say" value the default value in order to avoid users being male by default.

Note: The value 99 for "rather not say" is in line what the sr_feuser_register and feuserextrafields extensions use.

### CODE REVIEW

**Comment by sbusemann** [comment]
Hi Oliver, I want to implement a different approach for the next major version. The default value "0" will change to "not choose" - 1 will stay female, 2 will stay "diverse", 3 will be male. An upgrade wizard will be shipped. If you want to use "rather not say" you can then overwrite the lang label.

**Comment by oliverklee** [comment]
> I want to implement a different approach for the next major version.

This has implications on some other extensions. I propose we two have a call to talk things through to make sure users/integrators won't run into problems.

**Comment by sbusemann** [comment]
The change will be marked as breaking change in the next major version for TYPO3 13.

**Comment by oliverklee** [comment]
Let's go the route we discussed at our call earlier today. Closing then.

**Comment by oliverklee** [comment]
@sbusemann As agreed on during our call, I've created a change to the Core. I'll appreciate reviews: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84441

**Pull request closed without merging**
