### PR TITLE
Password repeat not mandatory

### PR DESCRIPTION
**Pull request by webian**
There are use cases where is not needed to have a password repeat field.

This PR allows this use case to be satisfied.

### CODE REVIEW

**Comment by spoonerWeb** [comment]
As this is a feature which is very edge-case I'd vote against merging it.

**Comment by webian** [comment]
IMHO it is confirm password field that should be edge-case.
It's obsolete nowadays with password managers that generate random password and save it or with 2FA. There's also the option to recover password in the rare case that someone write it wrong while signing up.
Better to implement "show password" button instead of annoy users in the hope that they write the password correctly.

In any case devs have both options: password repeat and no password repeat. Without this patch password repeat is mandatory.

**Comment by spoonerWeb** [comment]
There are still a lot of people (e.g. 65% of Americans, see [article](https://www.passwordmanager.com/password-manager-trust-survey/)) that don't use a Password Manager.
Let's take a look at the biggest websites (Apple, Facebook, Google, Amazon). Only one having no repeat field on registration is Facebook. The other ones still use it.

I'm for adding a possibility to show the password and possibly also a password strength meter, but we should keep the password repeat field.

**Comment by sbusemann** [comment]
I agree with SpoonerWeb and will close the PR - thanks anyway.

**Comment by webian** [comment]
This patch doesn't force you to remove the confirm password field. You can still use it if you want.

Instead, this patch gives the possibility to not use that field. So I really don't understand how you guys think.

**Pull request closed without merging**
