### PR TITLE
fixes in2code-de/femanager#221

### PR DESCRIPTION
**Pull request by paulboenisch**
Fixed regex and empty config passes.

### CODE REVIEW

**Comment by sbusemann** [comment]
@paulboenisch do not use dsgvo as naming. Please rename it to gdpr as this more generic for international usage.

**Comment by Patta** [comment]
@paulboenisch or even better name it just privacyGuidelines

**Comment by paulboenisch** [comment]
@Patta I will go with shorter gdpr

**Comment by Patta** [comment]
@paulboenisch 
Ok, but a field should rather be named according to its general meaning and not according to a regulation, which are only a part of the data protection guidelines.

Why do you add a house number field? The address field contains street and house number, or do i get it wrong? Maybe you just need to change the label with typoscript in your site.

**Comment by paulboenisch** [comment]
@Patta I knew about Street and Number in one field. I needed separate field thou.

**Comment by No5251** [comment]
> @Patta I knew about Street and Number in one field. I needed separate field thou.

Correct way to achieve this: https://github.com/einpraegsam/femanagerextended

**Pull request closed without merging**
