### PR TITLE
[TASK] Remove dependencies of generic Extbase domain classes

### PR DESCRIPTION
**Pull request by theLine**
See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94654-GenericExtbaseDomainClasses.html

### CODE REVIEW

**Comment by theLine** [comment]
@sbusemann I was wondering, why this PR was closed (without any comment).
 Is there a particular reason or is there any other work that will resolve the deprecation or breaking change?   
I mean, the the `TYPO3\CMS\Extbase\Domain\Model\FrontendUser` and `TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup` objects were marked as [deprecated in TYPO3 CMS v11](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94654-GenericExtbaseDomainClasses.html) and were [removed in TYPO3 CMS v12](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html).

**Comment by sbusemann** [comment]
This was not on purpose - i removed old branches ( f.e. V11) - i think that closed the PR

**Comment by theLine** [comment]
ahh ok, thanks for the clarification and sorry for bothering 😅

**Comment by sbusemann** [comment]
@theLine the code is implented in the V12 Branch in the Early Access Repository - thanks for your contribution.

**Pull request closed without merging**
