### PR TITLE
Ollc . Phone line femanger.

### PR DESCRIPTION
**Pull request by Michaelmichaeljensen**
Addln phone line ofbristionsnettet. Ctalk/adln.

### CODE REVIEW

**Comment by Michaelmichaeljensen** [comment]
Opstretusnel  opdfull rights. The next  ollc  wordcapederly.  The ollc phone line  works  femanger. Regards Michael maindal  Jensen. Google

**Comment by Michaelmichaeljensen** [comment]
Close command

**Comment by Michaelmichaeljensen** [comment]
Appln line comp/le*/unt.

**Comment by Michaelmichaeljensen** [comment]
Phone line. Ofbistrationsnettet. Ctalk  adln /Addln. Complete. Regards Michael maindal jensen.

**Comment by Michaelmichaeljensen** [comment]
Subtriconclution condition Red.

**Comment by Michaelmichaeljensen** [comment]
Coming closer though. of it maby it should be an Ai instead it just  need offstrilamation and a user mab  ore fluretement. Ther are many ways option object in ore lusiferment. Ore oplixtuer programing then it's done.let's se what choises to make regards.right now  need  the logfdement then the phone line is complete.

**Comment by Michaelmichaeljensen** [comment]
Now need  a buildin  controler  user

**Comment by einpraegsam** [comment]
Spam

**Pull request closed without merging**
